name: Sync Calendar

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run script
        env:
          GITHUB_ACTIONS: true
          CALDAV_USERNAME: ${{ secrets.CALDAV_USERNAME }}
          CALDAV_PASSWORD: ${{ secrets.CALDAV_PASSWORD }}
          CALDAV_SERVER_URL: ${{ secrets.CALDAV_SERVER_URL }}
        run: node index.mjs

      - name: Push to another repository
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          if [ ! -f filtered.ics ]; then
            echo "filtered.ics not found!"
            exit 1
          fi

          git clone https://${{ secrets.TARGET_REPO_TOKEN }}@github.com/${{ secrets.TARGET_REPO_NAME }}.git target-repo
          cp filtered.ics target-repo/
          cd target-repo

          git add filtered.ics
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit --amend -m "Update filtered.ics"
            git push -f
          fi
