name: Sync Calendar

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run script
        env:
          GITHUB_ACTIONS: true
          CALDAV_USERNAME: ${{ secrets.CALDAV_USERNAME }}
          CALDAV_PASSWORD: ${{ secrets.CALDAV_PASSWORD }}
          CALDAV_SERVER_URL: ${{ secrets.CALDAV_SERVER_URL }}
        run: node index.mjs

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add filtered.ics
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update filtered.ics" && git push origin ics) 